# build stage
FROM golang:1.15.6-buster as builder
WORKDIR /go/src/app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build .

# output stage
FROM alpine:3.7
WORKDIR /app
COPY --from=builder /go/src/app/books-service /app/
ENV HOST "0.0.0.0"
ENV PORT 9000
EXPOSE 9000
CMD ["./hello"]